/*
    Golden-vector generator for the physics port: compiled against the flagship's own sources,
    so the vectors ARE the C++ implementation's answers rather than anyone's transcription.

    Regeneration (from this repository's root, with a tron-grid-lite checkout beside it and the
    MSVC environment loaded). The flagship deleted its stepBody in its PR #95, so the checkout
    must be the commit before that deletion (d83c378^), and the bvh include path is needed too:

        cl /std:c++20 /EHsc /O2 /utf-8 tools\generate_physics_goldens.cpp ^
           ..\tron-grid-lite\src\geometry.cpp ..\tron-grid-lite\src\roster.cpp ^
           ..\tron-grid-lite\src\program_library.cpp ..\tron-grid-lite\src\loader_os.cpp ^
           /I..\tron-grid-lite\src /I..\tron-grid-lite\libs\math\include ^
           /I..\tron-grid-lite\libs\program-abi\include ^
           /Fe:generate_physics_goldens.exe
        generate_physics_goldens.exe tests\data

    The ground vectors are compared bit-exactly (the arithmetic is hash, smoothstep and floor -
    no libm anywhere), the step vectors with a tolerance (yaw goes through sin and cos, and no
    two libms agree in the last bit).

    Copyright (C) 2026 Matej Gomboc <https://github.com/ai-quokka-wannabe/master-control>
    GPL-3.0-or-later, as everything here.
*/

#include "geometry.hpp"
#include "roster.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <numbers>
#include <vector>

#include <cstdlib>
#include <fstream>

//! printf-shaped output onto a stream: the goldens keep their exact text format.
template<typename... Args>
void print(std::ofstream& file, const char* format, Args... args)
{
    char line[512];
    const int length{std::snprintf(line, sizeof(line), format, args...)};
    file.write(line, (length < 0) ? 0 : ((length >= static_cast<int>(sizeof(line))) ? static_cast<int>(sizeof(line)) - 1 : length));
}

// stepBody has external linkage in roster.cpp; the flagship's header does not declare it, so
// this consumer does - the free-function seam the audit named, used as one.
namespace RosterLib
{
    void stepBody(Creature& creature, const GroundFunction& ground);
}

namespace
{

    // The flagship's GRID_FLOOR_CONFIG: cells, cell_size and height overridden, the relief
    // fields left at the struct's own defaults.
    constexpr GridFloorConfig FLOOR{.cells = 64u, .cell_size = 2.0f, .height = 0.0f};

    [[nodiscard]] std::uint32_t bits(float value)
    {
        std::uint32_t out{};
        std::memcpy(&out, &value, sizeof(out));
        return out;
    }

}

/*!
    The output directory, judged before a file is touched: a plain directory name or path that
    never climbs - no `..` component - so an argument cannot steer this tool's two fixed file
    names anywhere surprising. The files themselves are opened as streams, never with fopen's
    permissive default mode.
*/
[[nodiscard]] std::filesystem::path judgedOutputDirectory(const int argc, char** argv)
{
    const std::filesystem::path out_dir{argc > 1 ? argv[1] : "."};
    for (const std::filesystem::path& component : out_dir) {
        if (component == "..") {
            std::fprintf(stderr, "The output directory never climbs: no .. component.\n");
            std::exit(EXIT_FAILURE);
        }
    }
    return out_dir;
}

[[nodiscard]] std::ofstream openGolden(const std::filesystem::path& out_dir, const char* name)
{
    std::ofstream file{out_dir / name, std::ios::binary | std::ios::trunc};
    if (!file) {
        std::fprintf(stderr, "Could not open %s for writing.\n", name);
        std::exit(EXIT_FAILURE);
    }
    return file;
}

int main(int argc, char** argv)
{
    const std::filesystem::path out_dir{judgedOutputDirectory(argc, argv)};
    std::filesystem::create_directories(out_dir);

    // ---- Ground: a sweep that exercises cells, boundaries, negatives and the edge clamp. ----
    {
        std::ofstream file{openGolden(out_dir, "ground_goldens.txt")};
        print(file, "# x_bits z_bits height_bits - gridMeshHeight over the flagship's GRID_FLOOR_CONFIG, f32 bit patterns in hex.\n");
        print(file, "# Generated by tools/generate_physics_goldens.cpp from tron-grid-lite's geometry.cpp. Bit-exact comparison.\n");

        std::vector<float> coordinates;
        for (int step{-70}; step <= 70; step += 7) {
            coordinates.push_back(static_cast<float>(step));
        }
        // Off-lattice fractions, cell boundaries, and far outside the floor for the clamp.
        for (const float extra : {0.25f, 0.5f, 1.75f, -3.3f, 63.999f, -64.0f, 64.0f, 200.0f, -200.0f, 31.415f}) {
            coordinates.push_back(extra);
        }

        for (const float x : coordinates) {
            for (const float z : coordinates) {
                const float height{gridMeshHeight(x, z, FLOOR)};
                print(file, "%08X %08X %08X\n", bits(x), bits(z), bits(height));
            }
        }
    }

    // ---- Step: one scripted life - fall, land, walk, arc, garbage intent, stop. ----
    {
        std::ofstream file{openGolden(out_dir, "step_goldens.txt")};
        print(file, "# tick px py pz yaw vx vy vz forward_speed turn_rate vocalisation grounded contacts\n");
        print(file, "# Generated by tools/generate_physics_goldens.cpp from tron-grid-lite's roster.cpp stepBody\n");
        print(file, "# over gridMeshHeight ground, default first body bounds. Tolerance comparison (sin/cos in the arc).\n");

        RosterLib::GroundFunction ground{[](float x, float z) {
            return gridMeshHeight(x, z, FLOOR);
        }};

        RosterLib::Creature creature{};
        creature.body.creature_id = 100u;
        creature.body.max_forward_speed = 1.0f;
        creature.body.max_turn_rate = std::numbers::pi_v<float> / 2.0f;
        creature.body.max_vocalisation_strength = 1.0f;
        creature.body.max_contact_count = 4u;

        // Spawn two metres above the drawn floor: the first act is ballistic, then a landing.
        creature.pose.position = MathLib::Vec3{0.0f, ground(0.0f, 6.0f) + RosterLib::BODY_HALF_HEIGHT + 2.0f, 6.0f};
        creature.grounded = false;

        for (std::uint32_t tick{0u}; tick < 256u; ++tick) {
            TglActions intent{};
            if (tick < 40u) {
                // Falling: any intent is moot, traction is absent.
            } else if (tick < 100u) {
                intent.desired_forward_speed = 1.0f;
            } else if (tick < 160u) {
                intent.desired_forward_speed = 0.5f;
                intent.desired_turn_rate = 1.0f;
                intent.vocalisation_strength = 0.8f;
            } else if (tick == 160u) {
                // Garbage: sanitise must make this zero intent, never a bound.
                intent.desired_forward_speed = std::numeric_limits<float>::quiet_NaN();
                intent.desired_turn_rate = std::numeric_limits<float>::infinity();
                intent.vocalisation_strength = -3.0f;
            } else if (tick < 220u) {
                intent.desired_forward_speed = -2.5f; // Clamped to the body's -1.
                intent.desired_turn_rate = -0.25f;
            }
            RosterLib::sanitiseAndClamp(intent, creature.body);
            creature.staged = intent;

            RosterLib::stepBody(creature, ground);

            print(file, "%u %.9g %.9g %.9g %.9g %.9g %.9g %.9g %.9g %.9g %.9g %u %u\n", tick, creature.pose.position.x, creature.pose.position.y,
                creature.pose.position.z, creature.pose.yaw, creature.velocity.x, creature.velocity.y, creature.velocity.z, creature.forward_speed,
                creature.turn_rate, creature.vocalisation, creature.grounded ? 1u : 0u, static_cast<unsigned>(creature.contacts.size()));
        }
    }

    std::printf("goldens written to %s\n", out_dir.string().c_str());
    return 0;
}
